<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Swashbuckle.AspNetCore"/>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Audit.Application\Audit.Application.csproj" />
		<ProjectReference Include="..\Audit.Infrastructure\Audit.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\Libs\EventBus.ServiceBus\EventBus.ServiceBus.csproj" />
		<ProjectReference Include="..\..\..\Libs\EventContracts\EventContracts.csproj" />
	</ItemGroup>

</Project>
